<?php

function mydata_schema() {
  $schema['cities'] = array(
    'fields' => array(
      'id'=>array(
        'type'=>'serial',
        'not null' => TRUE,
      ),
      'name'=>array(
        'type' => 'varchar',
        'length' => 40,
        'not null' => TRUE,
      ),
      'code'=>array(
        'type' => 'varchar',
        'length' => 2,
        'not null' => TRUE,
      ),

    ),
    'primary key' => array('id'),
  );

  return $schema;

}